-- funksii dlya raboti s vremenem

SELECT SYSDATETIME() AS CurrentDate
SELECT YEAR(SYSDATETIME()) AS CurrentYear
SELECT MONTH(SYSDATETIME()) AS CurrentMonth
SELECT DAY(SYSDATETIME()) AS CurrentDay

SELECT MONTH('19800223') AS CurrentYear

SELECT DATEDIFF(YEAR,'1980/07/10' ,SYSDATETIME()) AS MyAge

SELECT DATEDIFF(DAY,'1980/07/10' ,SYSDATETIME()) AS MyAgeDays

SELECT DATEDIFF(HOUR,'1980/07/10' ,SYSDATETIME()) AS MyAgeHours

SELECT DATEDIFF(SECOND,'1980/07/10' ,SYSDATETIME()) AS MyAgeSecond